project_id = "bdavaqclmlsufstzpjrj"

[functions.create-super-admin]
verify_jwt = false

[functions.init-super-admins]
verify_jwt = false

[functions.evaluate-lesson-responses]
verify_jwt = true

[functions.suggest-question-difficulty]
verify_jwt = true

[functions.create-user-admin]
verify_jwt = true

[functions.mercadopago-oauth]
verify_jwt = true
